version: '3.8'
services:
  postgresql:
    image: timescale/timescaledb:latest-pg14
    container_name: postgre-timescaledb
    ports:
      - '54321:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypostgre
