server:
  port: 8090
spring:
  application:
    name: springboot-kafka-ex
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      first: topic1
      msg-filter: msg-filter
      second: topic2
      dto-list: dto-list
      test: testTopic
      group-test: group-test
      check-partition: check-partition
      stock-price: stock-price
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: mypostgre
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# logging:
#   level:
#     root: INFO
#   file:
#     name: D:/source/java-workspace/springboot-kafka-ex/logs/application.log
#     encoding: UTF-8
#     max-size: 10MB
#     max-history: 30
