server:
  port: 8090
spring:
  application:
    name: springboot-kafka-ex
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      first: topic1
      second: topic2
    consumer:
      group-id: my-group
      auto-offset-reset: earliest

